name: Tests                        

on:
  - push

jobs:
    test:
        runs-on: ubuntu-latest    

        steps:
        - uses: actions/checkout@v6 

        - name: Setup Python         
          uses: actions/setup-python@v6
          with:
            python-version: '3.13'

        - name: Install dependencies 
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Ensure browser are installed
          run: python -m playwright install chromium --with-deps  

        - name: Run tests
          env:
            STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
            STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
            LOCKED_USERNAME: ${{ secrets.LOCKED_USERNAME }}
            LOCKED_PASSWORD: ${{ secrets.LOCKED_PASSWORD }}
            INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
            INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
            API_KEY: ${{ secrets.API_KEY }}
          run: pytest 